services:
  honeypot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EVENTS_URL=${EVENTS_URL}
      - P0F_SOCKET_PATH=/var/run/p0f.socket
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - API_KEY=${API_KEY}
    volumes:
      - /run/p0f/p0f.socket:/var/run/p0f.socket
      - ./config.yml:/config.yml
    network_mode: host
